-- JJ Studio portfolio Supabase setup
-- Run this file in Supabase Dashboard -> SQL Editor.
-- It creates the tables used by the current Next.js project and allows public form inserts only.

create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  name text,
  contact text,
  customer_type text,
  project_type text,
  budget text,
  timeline text,
  description text,
  service text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.course_signups (
  id bigint generated by default as identity primary key,
  name text,
  wechat text,
  plan text,
  platform text,
  goal text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.beauty_bookings (
  id bigint generated by default as identity primary key,
  service_name text,
  booking_date text,
  booking_time text,
  customer_name text,
  phone text,
  note text,
  first_visit boolean default true,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.private_orders (
  id bigint generated by default as identity primary key,
  items jsonb,
  total_amount numeric default 0,
  customer_name text,
  phone text,
  wechat text,
  address text,
  expected_delivery text,
  note text,
  group_buy boolean default false,
  status text not null default 'pending_contact',
  created_at timestamptz not null default now()
);

create table if not exists public.student_project_posts (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  price text,
  condition text,
  contact text,
  location text,
  description text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create index if not exists contact_inquiries_created_at_idx on public.contact_inquiries(created_at desc);
create index if not exists course_signups_created_at_idx on public.course_signups(created_at desc);
create index if not exists beauty_bookings_created_at_idx on public.beauty_bookings(created_at desc);
create index if not exists private_orders_created_at_idx on public.private_orders(created_at desc);
create index if not exists student_project_posts_created_at_idx on public.student_project_posts(created_at desc);

alter table public.contact_inquiries enable row level security;
alter table public.course_signups enable row level security;
alter table public.beauty_bookings enable row level security;
alter table public.private_orders enable row level security;
alter table public.student_project_posts enable row level security;

drop policy if exists "anon can insert contact inquiries" on public.contact_inquiries;
drop policy if exists "anon can insert course signups" on public.course_signups;
drop policy if exists "anon can insert beauty bookings" on public.beauty_bookings;
drop policy if exists "anon can insert private orders" on public.private_orders;
drop policy if exists "anon can insert student project posts" on public.student_project_posts;

create policy "anon can insert contact inquiries"
on public.contact_inquiries
for insert
to anon
with check (true);

create policy "anon can insert course signups"
on public.course_signups
for insert
to anon
with check (true);

create policy "anon can insert beauty bookings"
on public.beauty_bookings
for insert
to anon
with check (true);

create policy "anon can insert private orders"
on public.private_orders
for insert
to anon
with check (true);

create policy "anon can insert student project posts"
on public.student_project_posts
for insert
to anon
with check (true);
